### ISSUE TITLE
Where did the code limit detectron2 only detect human?

### ISSUE THREAD

**Issue by kylehh** [videoflow/videoflow-contrib#31]
From the code it seems that it's doing normal detection
Why the prediction only return human labels ?

https://github.com/videoflow/videoflow-contrib/blob/3ef2b8cb3cf467bab8ff3ae2db630d1f5de0ae05/detectron2/videoflow_contrib/detectron2/humanpose.py#L171

**Comment by jadielam** [comment]
The config file is what limits the code to return only human labels:

https://github.com/videoflow/videoflow-contrib/blob/3ef2b8cb3cf467bab8ff3ae2db630d1f5de0ae05/detectron2/videoflow_contrib/detectron2/configs/Base-Keypoint-RCNN-FPN.yaml

The pretrained model was trained with a config file with only one class (humans) and two heads: detections and keypoints.

**Comment by kylehh** [comment]
Thanks for the reply Jadiel!
The information was very helpful
